### ISSUE TITLE
[easy task] Add preview.png to root of this repo

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes-expression-box-swarm-visualizer#2]
If you would like to pick this issue up, please comment on the issue to let us know you're working on it :) 

## Task: 
Add preview.png to the root of this repository

## How to do this

1. Go to the repo README, and follow instructions to clone and install this repository.
2. Run `npm run dev` and visit http://localhost:3456
3. Capture a screenshot of the application in action! Try to avoid extra/un-needed whitespace, and try to make it square-ish (this doesn't have to be exact).  
4. Save it in the root of this repo, commit it, and make a PR :tada: 

Context: these previews will be used here: http://bluegenes.apps.intermine.org/default/debug/tool-store - you can look for other repos under intermine to find similar tasks for other bluegenes-* repositories as several tools are missing previews.

 
### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), pop by to say hi on [chat](http://chat.intermine.org) or if needed email yo@intermine.org <3

**Comment by julianDii** [comment]
I do it.

**Comment by yochannah** [comment]
Awesome, thanks! Let us know if you have any questions :)

**Comment by julianDii** [comment]
I can not push my branch to the repo.

**Comment by yochannah** [comment]
Hey @julianDii! What I'd suggest: fork this repository (top right corner) then push to your own fork. Once that's done, you can create a pull request (but let me know if you get stuck on any of the steps!) 

Here's a nice little guide from GitHub: https://guides.github.com/activities/forking/

**Comment by yochannah** [comment]
fixed by #3
